# twitter developer keys for rs algorithmic analytics
# In order to access Twitter API. Please enter your 
# Twitter Developer credentials
Twitter_API_ConsumerKey: XXXXXXXXXXXXXXXXXXXXXXX
Twitter_API_ConsumerSecret: XXXXXXXXXXXXXXXXXXXXXXX
Twitter_API_AccessToken: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Twitter_API_AccessSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Twitter_API_BearerToken: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX