# twitter developer keys for rs algorithmic analytics
Twitter_API_ConsumerKey: XBS7HYi6rXB1ijQ4vZljBFQhC
Twitter_API_ConsumerSecret: KWJVi9b9gWyxgbHM7vC0wB4DVYCcybq2dof2jogKxEhBP87oRs
Twitter_API_AccessToken: 1412721250707906561-6UxChUTmW3E8puPtCu9IoIi0RcGe84
Twitter_API_AccessSecret: LQmO9LysVsV73sz64zxQnr7NbNA2KCVNdxBdDzEdTJ1N9
Twitter_API_BearerToken: AAAAAAAAAAAAAAAAAAAAAOdtRgEAAAAAZnPBl4ouZXmbGd%2FgmYfivmDP77Y%3DK2gKZbvsGtnSvVjyKLj3AphqS2UzxXOjiAADBJabDYKffFEfkP